export interface ProjectCardData {
  id: string;
  title: string;
  shortDescription: string;
  techStack: string;
  category: "AI" | "Full-Stack" | "Backend" | "Frontend";
  outcomes: string[];
}

export interface ProjectDetailData extends ProjectCardData {
  dates: string;
  organization: string;
  whatBuilt: string[];
  role: string;
  technicalContributions: string[];
  techStackFull: string[];
  outcome: string[];
  repository?: string;
}

export const projectCards: ProjectCardData[] = [
  {
    id: "disaster-rag",
    title: "AI-Based Disaster Scenario Generation System",
    shortDescription: "RAG + Large Language Models",
    techStack: "LLMs, RAG, LangChain, FAISS, Docker",
    category: "AI",
    outcomes: ["Research-grade", "Multi-source RAG"],
  },
  {
    id: "posture-detection",
    title: "AI-Based Posture Detection and Feedback System",
    shortDescription: "Real-time computer vision for exercise analysis",
    techStack: "Python, Computer Vision, MediaPipe, OpenCV",
    category: "AI",
    outcomes: ["Real-time", "Low-latency"],
  },
  {
    id: "shebots",
    title: "SheBots — AI-Powered Academic Support Chatbot",
    shortDescription: "Bilingual conversational AI for academic support",
    techStack: "FastAPI, RAG, LangChain, GPT-4, Docker",
    category: "AI",
    outcomes: ["Production", "Bilingual"],
  },
  {
    id: "inflowchat",
    title: "InflowChat — Enterprise AI Chatbot",
    shortDescription: "Production-ready enterprise chatbot platform",
    techStack: "React, TypeScript, Gemini API, FAISS",
    category: "Frontend",
    outcomes: ["Production", "Enterprise"],
  },
  {
    id: "cafe-kiosk",
    title: "AI-Based Voice Recognition Café Kiosk",
    shortDescription: "Fine-tuned LLaMA for conversational ordering",
    techStack: "LLaMA3, FastAPI, NLP, Fine-Tuning",
    category: "AI",
    outcomes: ["+10% accuracy", "Fine-tuned"],
  },
  {
    id: "transportation-kiosk",
    title: "길:벗 (VISIONED) — Accessible Transportation Kiosk",
    shortDescription: "Voice-driven public transportation kiosk for accessibility",
    techStack: "Node.js, Express, Google Cloud APIs, React",
    category: "Full-Stack",
    outcomes: ["Accessibility", "Voice-driven"],
  },
  {
    id: "kert-website",
    title: "KERT Cybersecurity Club Website",
    shortDescription: "Official website for university cybersecurity club",
    techStack: "Java, Spring Boot, React, Docker",
    category: "Backend",
    outcomes: ["Deployed", "Secure API"],
  },
];

export const projectDetails: Record<string, ProjectDetailData> = {
  "disaster-rag": {
    id: "disaster-rag",
    title: "AI-Based Disaster Scenario Generation System",
    shortDescription: "RAG + Large Language Models",
    techStack: "LLMs, RAG, LangChain, FAISS, Docker",
    category: "AI",
    outcomes: ["Research-grade", "Multi-source RAG"],
    dates: "Oct 2025 – Dec 2025",
    organization: "Intelligent Software Systems Lab",
    whatBuilt: [
      "Designed and implemented a multi-source Retrieval-Augmented Generation (RAG) system for disaster scenario generation.",
      "Integrated heterogeneous data sources including disaster response manuals, legal documents, population statistics, and geo-spatial data.",
      "Built an end-to-end pipeline that converts structured and unstructured data (CSV, PDF, GeoJSON) into vector embeddings for semantic retrieval.",
    ],
    role: "Backend and AI pipeline developer.",
    technicalContributions: [
      "Implemented document ingestion and preprocessing pipelines for multiple formats, ensuring consistent chunking and metadata handling.",
      "Built vector search using FAISS to support accurate semantic retrieval across large, mixed datasets.",
      "Implemented LLM routing and orchestration using LangGraph, enabling model-agnostic support for GPT, LLaMA, and Gemini.",
      "Applied prompt engineering, response validation, and fallback strategies to reduce hallucinations and improve system reliability.",
      "Modularized the system into microservices using Docker to isolate ingestion, retrieval, and generation components.",
    ],
    techStackFull: [
      "Large Language Models (GPT, LLaMA, Gemini)",
      "Retrieval-Augmented Generation (RAG)",
      "LangChain",
      "LangGraph",
      "FAISS",
      "Python",
      "Docker",
      "Git",
    ],
    outcome: [
      "Achieved reliable, context-aware disaster scenario generation suitable for research and policy-level analysis.",
      "Improved retrieval accuracy and response consistency across heterogeneous data sources.",
      "Delivered a research-grade system extensible to additional data domains and models.",
    ],
    repository: "https://github.com/NishthaLath/Disaster_Management_RAG_System",
  },
  "posture-detection": {
    id: "posture-detection",
    title: "AI-Based Posture Detection and Feedback System",
    shortDescription: "Real-time computer vision for exercise analysis",
    techStack: "Python, Computer Vision, MediaPipe, OpenCV",
    category: "AI",
    outcomes: ["Real-time", "Low-latency"],
    dates: "Sep 2025 – Dec 2025",
    organization: "Kyungpook National University",
    whatBuilt: [
      "Developed a real-time posture detection and feedback system for exercise analysis using computer vision.",
      "Implemented camera-based pose estimation to extract skeletal keypoints from live video streams.",
      "Evaluated posture correctness through joint angle computation and geometric analysis.",
    ],
    role: "Sole developer.",
    technicalContributions: [
      "Integrated MediaPipe Pose for real-time keypoint detection.",
      "Implemented joint angle calculation logic to detect incorrect posture during exercises.",
      "Designed a real-time feedback loop that visually highlights posture errors during movement.",
      "Optimized the system to run efficiently on standard consumer hardware without requiring GPUs or specialized sensors.",
      "Designed the system architecture to be easily extendable to additional exercises.",
    ],
    techStackFull: [
      "Python",
      "Computer Vision",
      "MediaPipe Pose",
      "OpenCV",
      "Real-Time Video Processing",
      "Joint Angle Analysis",
    ],
    outcome: [
      "Delivered a low-latency posture analysis system suitable for beginner-level fitness and rehabilitation use.",
      "Demonstrated practical application of pose estimation in real-time feedback systems.",
    ],
    repository: "https://github.com/AI-Personal-Trainer/Posture_Angles_Extractor",
  },
  shebots: {
    id: "shebots",
    title: "SheBots — AI-Powered Academic Support Chatbot",
    shortDescription: "Bilingual conversational AI for academic support",
    techStack: "FastAPI, RAG, LangChain, GPT-4, Docker",
    category: "AI",
    outcomes: ["Production", "Bilingual"],
    dates: "Sep 2025 – Dec 2025",
    organization: "Kyungpook National University",
    whatBuilt: [
      "Designed and developed a bilingual (Korean/English) AI chatbot for academic and administrative support within the Computer Science department.",
      "Implemented Retrieval-Augmented Generation to answer queries based on structured university documents and manuals.",
    ],
    role: "Lead backend and AI developer.",
    technicalContributions: [
      "Designed a modular backend architecture separating frontend, LLM service, and RAG service.",
      "Implemented document ingestion, chunking strategies, and vector indexing using FAISS.",
      "Integrated GPT-4.1 and GPT-5 APIs with multilingual query handling and context-aware response generation.",
      "Optimized prompt design and retrieval strategies to improve answer accuracy for academic Q&A.",
      "Deployed the system using Docker and tested under real usage constraints including latency, concurrency, and resource limits.",
    ],
    techStackFull: [
      "FastAPI",
      "Retrieval-Augmented Generation (RAG)",
      "LangChain",
      "FAISS",
      "GPT-4.1 / GPT-5 APIs",
      "Docker",
      "Tailwind CSS",
    ],
    outcome: [
      "Deployed a production-ready chatbot serving real users.",
      "Achieved stable performance and high response accuracy under real-world usage conditions.",
    ],
    repository: "https://github.com/orgs/SheBots/repositories",
  },
  inflowchat: {
    id: "inflowchat",
    title: "InflowChat — Enterprise AI Chatbot",
    shortDescription: "Production-ready enterprise chatbot platform",
    techStack: "React, TypeScript, Gemini API, FAISS",
    category: "Frontend",
    outcomes: ["Production", "Enterprise"],
    dates: "Dec 2024 – Jan 2025",
    organization: "RikkeiSoft Corporation (Internship)",
    whatBuilt: [
      "Contributed to the development of an enterprise AI chatbot platform for internal company queries and document-based information retrieval.",
    ],
    role: "Sole frontend developer.",
    technicalContributions: [
      "Designed and implemented user and admin interfaces using React (TypeScript).",
      "Built role-based UI flows distinguishing general users and administrators.",
      "Implemented admin dashboards for prompt configuration, document management, and system control.",
      "Integrated frontend with backend APIs handling LLM inference and vector retrieval.",
      "Collaborated with backend engineers to ensure smooth API contracts and reliable UI behavior.",
    ],
    techStackFull: [
      "React.js (TypeScript)",
      "Tailwind CSS",
      "Axios",
      "Gemini API",
      "FAISS",
      "PostgreSQL",
      "JWT",
      "Google SSO",
      "Git",
    ],
    outcome: [
      "Delivered a production-ready frontend used in internal company workflows.",
      "Improved usability and administrative control over AI system behavior.",
    ],
    repository: "https://github.com/NishthaLath/InflowChat_Chatbot_Frontend",
  },
  "cafe-kiosk": {
    id: "cafe-kiosk",
    title: "AI-Based Voice Recognition Café Kiosk",
    shortDescription: "Fine-tuned LLaMA for conversational ordering",
    techStack: "LLaMA3, FastAPI, NLP, Fine-Tuning",
    category: "AI",
    outcomes: ["+10% accuracy", "Fine-tuned"],
    dates: "Sep 2024 – Dec 2024",
    organization: "Capstone Project (Industry-Collaborated)",
    whatBuilt: [
      "Upgraded an existing voice-based café ordering kiosk by replacing a RASA-based NLP system with a fine-tuned LLaMA3 model.",
    ],
    role: "AI system and architecture lead.",
    technicalContributions: [
      "Fine-tuned LLaMA3 for Korean conversational AI using Unsloth.",
      "Processed over 140,000 conversational data points including ambiguous and multi-intent orders.",
      "Conducted extensive testing with 100+ input-response scenarios to improve error handling and contextual understanding.",
      "Designed a modular system integrating Google Cloud Speech-to-Text with backend services.",
      "Implemented support for complex order modifications, substitutions, and multilingual expansion.",
    ],
    techStackFull: [
      "LLaMA3",
      "NLP",
      "Fine-Tuning (Unsloth)",
      "FastAPI",
      "Spring Boot",
      "PyQT",
      "MySQL",
      "Google Cloud STT",
    ],
    outcome: [
      "Achieved over 10% improvement in response accuracy and efficiency.",
      "Delivered a scalable, voice-driven kiosk system suitable for real retail environments.",
    ],
    repository: "https://github.com/orgs/AI-coffee-Kiosk/repositories",
  },
  "transportation-kiosk": {
    id: "transportation-kiosk",
    title: "길:벗 (VISIONED) — Accessible Transportation Kiosk",
    shortDescription: "Voice-driven public transportation kiosk for accessibility",
    techStack: "Node.js, Express, Google Cloud APIs, React",
    category: "Full-Stack",
    outcomes: ["Accessibility", "Voice-driven"],
    dates: "Oct 2024 – Nov 2024",
    organization: "Kyungpook National University",
    whatBuilt: [
      "Developed an accessible public transportation kiosk tailored for seniors and users with limited mobility.",
    ],
    role: "Backend lead and API developer.",
    technicalContributions: [
      "Designed and implemented backend APIs using Node.js and Express.",
      "Integrated Google Cloud Speech-to-Text and Text-to-Speech for voice-based interaction.",
      "Implemented real-time route recommendations using Google Maps API.",
      "Optimized server-side performance for real-time data handling.",
      "Collaborated with frontend designers to ensure accessibility-focused UX.",
    ],
    techStackFull: [
      "Node.js",
      "Express.js",
      "Google Cloud STT/TTS",
      "Google Maps API",
      "React",
      "GitHub",
    ],
    outcome: [
      "Delivered a functional, voice-driven kiosk prototype emphasizing accessibility.",
      "Demonstrated social impact aligned with inclusive mobility goals.",
    ],
    repository: "https://github.com/orgs/VISIONED-KNU/repositories",
  },
  "kert-website": {
    id: "kert-website",
    title: "KERT Cybersecurity Club Website",
    shortDescription: "Official website for university cybersecurity club",
    techStack: "Java, Spring Boot, React, Docker",
    category: "Backend",
    outcomes: ["Deployed", "Secure API"],
    dates: "May 2024 – Oct 2024",
    organization: "Kyungpook National University",
    whatBuilt: [
      "Developed the official website for the university cybersecurity club as a centralized information platform.",
    ],
    role: "Backend developer.",
    technicalContributions: [
      "Designed and implemented secure RESTful APIs using Java and Spring Boot.",
      "Implemented authentication and backend logic with Spring Security.",
      "Designed database schemas using JPA/Hibernate with H2 for testing.",
      "Deployed the system using Docker to ensure environment consistency.",
      "Collaborated with frontend developers using React.",
    ],
    techStackFull: [
      "Java",
      "Spring Boot",
      "Spring Security",
      "JPA/Hibernate",
      "H2 Database",
      "Docker",
      "React",
    ],
    outcome: [
      "Deployed a stable, secure backend for a real student organization.",
      "Improved communication and visibility for club activities.",
    ],
    repository: "https://github.com/NishthaLath/KERT_Backend",
  },
};

// Korean translations
export const koProjectCards: ProjectCardData[] = [
  {
    id: "disaster-rag",
    title: "AI 기반 재난 시나리오 생성 시스템",
    shortDescription: "RAG + 거대 언어 모델",
    techStack: "LLMs, RAG, LangChain, FAISS, Docker",
    category: "AI",
    outcomes: ["연구 수준", "다중 소스 RAG"],
  },
  {
    id: "posture-detection",
    title: "AI 기반 자세 감지 및 피드백 시스템",
    shortDescription: "운동 분석을 위한 실시간 컴퓨터 비전",
    techStack: "Python, Computer Vision, MediaPipe, OpenCV",
    category: "AI",
    outcomes: ["실시간", "저지연"],
  },
  {
    id: "shebots",
    title: "SheBots — AI 기반 학업 지원 챗봇",
    shortDescription: "학업 지원을 위한 이중 언어 대화형 AI",
    techStack: "FastAPI, RAG, LangChain, GPT-4, Docker",
    category: "AI",
    outcomes: ["배포 완료", "이중 언어"],
  },
  {
    id: "inflowchat",
    title: "InflowChat — 기업용 AI 챗봇",
    shortDescription: "배포 준비가 완료된 기업용 챗봇 플랫폼",
    techStack: "React, TypeScript, Gemini API, FAISS",
    category: "Frontend",
    outcomes: ["배포 완료", "기업용"],
  },
  {
    id: "cafe-kiosk",
    title: "AI 기반 음성 인식 카페 키오스크",
    shortDescription: "대화형 주문을 위한 파인튜닝된 LLaMA",
    techStack: "LLaMA3, FastAPI, NLP, Fine-Tuning",
    category: "AI",
    outcomes: ["+10% 정확도", "파인튜닝"],
  },
  {
    id: "transportation-kiosk",
    title: "길:벗 (VISIONED) — 접근성 중심 교통 키오스크",
    shortDescription: "음성 기반 대중교통 접근성 키오스크",
    techStack: "Node.js, Express, Google Cloud APIs, React",
    category: "Full-Stack",
    outcomes: ["접근성", "음성 기반"],
  },
  {
    id: "kert-website",
    title: "KERT 사이버보안 동아리 웹사이트",
    shortDescription: "대학 사이버보안 동아리 공식 웹사이트",
    techStack: "Java, Spring Boot, React, Docker",
    category: "Backend",
    outcomes: ["배포 완료", "안전한 API"],
  },
];

export const koProjectDetails: Record<string, ProjectDetailData> = {
  "disaster-rag": {
    id: "disaster-rag",
    title: "AI 기반 재난 시나리오 생성 시스템",
    shortDescription: "RAG + 거대 언어 모델",
    techStack: "LLMs, RAG, LangChain, FAISS, Docker",
    category: "AI",
    outcomes: ["연구 수준", "다중 소스 RAG"],
    dates: "2025년 10월 – 2025년 12월",
    organization: "지능형 소프트웨어 시스템 연구실",
    whatBuilt: [
      "재난 시나리오 생성을 위한 다중 소스 검색 증강 생성(RAG) 시스템을 설계하고 구현했습니다.",
      "재난 대응 매뉴얼, 법률 문서, 인구 통계, 지리 공간 데이터를 포함한 이기종 데이터 소스를 통합했습니다.",
      "구조화 및 비구조화 데이터(CSV, PDF, GeoJSON)를 시맨틱 검색을 위한 벡터 임베딩으로 변환하는 엔드투엔드 파이프라인을 구축했습니다.",
    ],
    role: "백엔드 및 AI 파이프라인 개발자.",
    technicalContributions: [
      "여러 형식에 대한 문서 수집 및 전처리 파이프라인을 구현하여 일관된 청킹과 메타데이터 처리를 보장했습니다.",
      "FAISS를 사용하여 대규모 혼합 데이터셋에서 정확한 시맨틱 검색을 지원하는 벡터 검색을 구축했습니다.",
      "LangGraph를 사용하여 LLM 라우팅 및 오케스트레이션을 구현하여 GPT, LLaMA, Gemini에 대한 모델 독립적 지원을 가능하게 했습니다.",
      "프롬프트 엔지니어링, 응답 검증, 폴백 전략을 적용하여 환각을 줄이고 시스템 안정성을 개선했습니다.",
      "Docker를 사용하여 수집, 검색, 생성 구성 요소를 격리하는 마이크로서비스로 시스템을 모듈화했습니다.",
    ],
    techStackFull: [
      "거대 언어 모델 (GPT, LLaMA, Gemini)",
      "검색 증강 생성 (RAG)",
      "LangChain",
      "LangGraph",
      "FAISS",
      "Python",
      "Docker",
      "Git",
    ],
    outcome: [
      "연구 및 정책 수준 분석에 적합한 신뢰할 수 있는 맥락 인식 재난 시나리오 생성을 달성했습니다.",
      "이기종 데이터 소스 전반에 걸쳐 검색 정확도와 응답 일관성을 개선했습니다.",
      "추가 데이터 도메인 및 모델로 확장 가능한 연구 수준의 시스템을 제공했습니다.",
    ],
    repository: "https://github.com/NishthaLath/Disaster_Management_RAG_System",
  },
  "posture-detection": {
    id: "posture-detection",
    title: "AI 기반 자세 감지 및 피드백 시스템",
    shortDescription: "운동 분석을 위한 실시간 컴퓨터 비전",
    techStack: "Python, Computer Vision, MediaPipe, OpenCV",
    category: "AI",
    outcomes: ["실시간", "저지연"],
    dates: "2025년 9월 – 2025년 12월",
    organization: "경북대학교",
    whatBuilt: [
      "컴퓨터 비전을 사용하여 운동 분석을 위한 실시간 자세 감지 및 피드백 시스템을 개발했습니다.",
      "라이브 비디오 스트림에서 골격 키포인트를 추출하기 위한 카메라 기반 자세 추정을 구현했습니다.",
      "관절 각도 계산 및 기하학적 분석을 통해 자세 정확성을 평가했습니다.",
    ],
    role: "단독 개발자.",
    technicalContributions: [
      "실시간 키포인트 감지를 위해 MediaPipe Pose를 통합했습니다.",
      "운동 중 잘못된 자세를 감지하기 위한 관절 각도 계산 로직을 구현했습니다.",
      "동작 중 자세 오류를 시각적으로 강조하는 실시간 피드백 루프를 설계했습니다.",
      "GPU나 특수 센서 없이 표준 소비자 하드웨어에서 효율적으로 실행되도록 시스템을 최적화했습니다.",
      "추가 운동으로 쉽게 확장할 수 있도록 시스템 아키텍처를 설계했습니다.",
    ],
    techStackFull: [
      "Python",
      "컴퓨터 비전",
      "MediaPipe Pose",
      "OpenCV",
      "실시간 비디오 처리",
      "관절 각도 분석",
    ],
    outcome: [
      "초보자 수준의 피트니스 및 재활 사용에 적합한 저지연 자세 분석 시스템을 제공했습니다.",
      "실시간 피드백 시스템에서 자세 추정의 실용적인 적용을 입증했습니다.",
    ],
    repository: "https://github.com/AI-Personal-Trainer/Posture_Angles_Extractor",
  },
  shebots: {
    id: "shebots",
    title: "SheBots — AI 기반 학업 지원 챗봇",
    shortDescription: "학업 지원을 위한 이중 언어 대화형 AI",
    techStack: "FastAPI, RAG, LangChain, GPT-4, Docker",
    category: "AI",
    outcomes: ["배포 완료", "이중 언어"],
    dates: "2025년 9월 – 2025년 12월",
    organization: "경북대학교",
    whatBuilt: [
      "컴퓨터공학과 내 학업 및 행정 지원을 위한 이중 언어(한국어/영어) AI 챗봇을 설계하고 개발했습니다.",
      "구조화된 대학 문서 및 매뉴얼을 기반으로 질의에 답변하기 위한 검색 증강 생성을 구현했습니다.",
    ],
    role: "백엔드 및 AI 리드 개발자.",
    technicalContributions: [
      "프론트엔드, LLM 서비스, RAG 서비스를 분리하는 모듈식 백엔드 아키텍처를 설계했습니다.",
      "FAISS를 사용하여 문서 수집, 청킹 전략, 벡터 인덱싱을 구현했습니다.",
      "다국어 쿼리 처리 및 맥락 인식 응답 생성과 함께 GPT-4.1 및 GPT-5 API를 통합했습니다.",
      "학업 Q&A에 대한 답변 정확도를 향상시키기 위해 프롬프트 설계 및 검색 전략을 최적화했습니다.",
      "지연 시간, 동시성, 리소스 제한을 포함한 실제 사용 제약 조건에서 Docker를 사용하여 시스템을 배포하고 테스트했습니다.",
    ],
    techStackFull: [
      "FastAPI",
      "검색 증강 생성 (RAG)",
      "LangChain",
      "FAISS",
      "GPT-4.1 / GPT-5 API",
      "Docker",
      "Tailwind CSS",
    ],
    outcome: [
      "실제 사용자에게 서비스를 제공하는 배포 준비가 완료된 챗봇을 배포했습니다.",
      "실제 사용 조건에서 안정적인 성능과 높은 응답 정확도를 달성했습니다.",
    ],
    repository: "https://github.com/orgs/SheBots/repositories",
  },
  inflowchat: {
    id: "inflowchat",
    title: "InflowChat — 기업용 AI 챗봇",
    shortDescription: "배포 준비가 완료된 기업용 챗봇 플랫폼",
    techStack: "React, TypeScript, Gemini API, FAISS",
    category: "Frontend",
    outcomes: ["배포 완료", "기업용"],
    dates: "2024년 12월 – 2025년 1월",
    organization: "RikkeiSoft Corporation (인턴십)",
    whatBuilt: [
      "내부 회사 문의 및 문서 기반 정보 검색을 위한 기업용 AI 챗봇 플랫폼 개발에 기여했습니다.",
    ],
    role: "단독 프론트엔드 개발자.",
    technicalContributions: [
      "React(TypeScript)를 사용하여 사용자 및 관리자 인터페이스를 설계하고 구현했습니다.",
      "일반 사용자와 관리자를 구분하는 역할 기반 UI 플로우를 구축했습니다.",
      "프롬프트 구성, 문서 관리, 시스템 제어를 위한 관리자 대시보드를 구현했습니다.",
      "LLM 추론 및 벡터 검색을 처리하는 백엔드 API와 프론트엔드를 통합했습니다.",
      "백엔드 엔지니어와 협력하여 원활한 API 계약과 안정적인 UI 동작을 보장했습니다.",
    ],
    techStackFull: [
      "React.js (TypeScript)",
      "Tailwind CSS",
      "Axios",
      "Gemini API",
      "FAISS",
      "PostgreSQL",
      "JWT",
      "Google SSO",
      "Git",
    ],
    outcome: [
      "내부 회사 워크플로에서 사용되는 배포 준비가 완료된 프론트엔드를 제공했습니다.",
      "AI 시스템 동작에 대한 사용성과 관리 제어를 개선했습니다.",
    ],
    repository: "https://github.com/NishthaLath/InflowChat_Chatbot_Frontend",
  },
  "cafe-kiosk": {
    id: "cafe-kiosk",
    title: "AI 기반 음성 인식 카페 키오스크",
    shortDescription: "대화형 주문을 위한 파인튜닝된 LLaMA",
    techStack: "LLaMA3, FastAPI, NLP, Fine-Tuning",
    category: "AI",
    outcomes: ["+10% 정확도", "파인튜닝"],
    dates: "2024년 9월 – 2024년 12월",
    organization: "캡스톤 프로젝트 (산학 협력)",
    whatBuilt: [
      "RASA 기반 NLP 시스템을 파인튜닝된 LLaMA3 모델로 교체하여 기존 음성 기반 카페 주문 키오스크를 업그레이드했습니다.",
    ],
    role: "AI 시스템 및 아키텍처 리드.",
    technicalContributions: [
      "Unsloth를 사용하여 한국어 대화형 AI를 위한 LLaMA3를 파인튜닝했습니다.",
      "모호하고 다중 의도 주문을 포함하여 140,000개 이상의 대화 데이터 포인트를 처리했습니다.",
      "오류 처리 및 맥락 이해를 개선하기 위해 100개 이상의 입력-응답 시나리오로 광범위한 테스트를 수행했습니다.",
      "Google Cloud Speech-to-Text를 백엔드 서비스와 통합하는 모듈식 시스템을 설계했습니다.",
      "복잡한 주문 수정, 대체 및 다국어 확장에 대한 지원을 구현했습니다.",
    ],
    techStackFull: [
      "LLaMA3",
      "NLP",
      "파인튜닝 (Unsloth)",
      "FastAPI",
      "Spring Boot",
      "PyQT",
      "MySQL",
      "Google Cloud STT",
    ],
    outcome: [
      "응답 정확도 및 효율성을 10% 이상 개선했습니다.",
      "실제 소매 환경에 적합한 확장 가능한 음성 기반 키오스크 시스템을 제공했습니다.",
    ],
    repository: "https://github.com/orgs/AI-coffee-Kiosk/repositories",
  },
  "transportation-kiosk": {
    id: "transportation-kiosk",
    title: "길:벗 (VISIONED) — 접근성 중심 교통 키오스크",
    shortDescription: "음성 기반 대중교통 접근성 키오스크",
    techStack: "Node.js, Express, Google Cloud APIs, React",
    category: "Full-Stack",
    outcomes: ["접근성", "음성 기반"],
    dates: "2024년 10월 – 2024년 11월",
    organization: "경북대학교",
    whatBuilt: [
      "고령자 및 거동이 불편한 사용자를 위한 접근성 중심 대중교통 키오스크를 개발했습니다.",
    ],
    role: "백엔드 리드 및 API 개발자.",
    technicalContributions: [
      "Node.js 및 Express를 사용하여 백엔드 API를 설계하고 구현했습니다.",
      "음성 기반 상호작용을 위해 Google Cloud Speech-to-Text 및 Text-to-Speech를 통합했습니다.",
      "Google Maps API를 사용하여 실시간 경로 추천을 구현했습니다.",
      "실시간 데이터 처리를 위한 서버 측 성능을 최적화했습니다.",
      "프론트엔드 디자이너와 협력하여 접근성 중심 UX를 보장했습니다.",
    ],
    techStackFull: [
      "Node.js",
      "Express.js",
      "Google Cloud STT/TTS",
      "Google Maps API",
      "React",
      "GitHub",
    ],
    outcome: [
      "접근성을 강조하는 기능적인 음성 기반 키오스크 프로토타입을 제공했습니다.",
      "포용적 이동성 목표에 부합하는 사회적 영향을 입증했습니다.",
    ],
    repository: "https://github.com/orgs/VISIONED-KNU/repositories",
  },
  "kert-website": {
    id: "kert-website",
    title: "KERT 사이버보안 동아리 웹사이트",
    shortDescription: "대학 사이버보안 동아리 공식 웹사이트",
    techStack: "Java, Spring Boot, React, Docker",
    category: "Backend",
    outcomes: ["배포 완료", "안전한 API"],
    dates: "2024년 5월 – 2024년 10월",
    organization: "경북대학교",
    whatBuilt: [
      "중앙 집중식 정보 플랫폼으로 대학 사이버보안 동아리 공식 웹사이트를 개발했습니다.",
    ],
    role: "백엔드 개발자.",
    technicalContributions: [
      "Java 및 Spring Boot를 사용하여 안전한 RESTful API를 설계하고 구현했습니다.",
      "Spring Security를 사용하여 인증 및 백엔드 로직을 구현했습니다.",
      "테스트용 H2와 함께 JPA/Hibernate를 사용하여 데이터베이스 스키마를 설계했습니다.",
      "환경 일관성을 보장하기 위해 Docker를 사용하여 시스템을 배포했습니다.",
      "React를 사용하는 프론트엔드 개발자와 협력했습니다.",
    ],
    techStackFull: [
      "Java",
      "Spring Boot",
      "Spring Security",
      "JPA/Hibernate",
      "H2 Database",
      "Docker",
      "React",
    ],
    outcome: [
      "실제 학생 조직을 위한 안정적이고 안전한 백엔드를 배포했습니다.",
      "동아리 활동에 대한 커뮤니케이션과 가시성을 개선했습니다.",
    ],
    repository: "https://github.com/NishthaLath/KERT_Backend",
  },
};
